version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install npm
          command: npm install
      - run:
          name: run test
          command: npm test