# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 20:11
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridhomepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('page', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.RichTextBlock()), ('heading2', wagtail.wagtailcore.blocks.RichTextBlock()), ('description', wagtail.wagtailcore.blocks.RichTextBlock()), ('background_image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('page', wagtail.wagtailcore.blocks.PageChooserBlock())))), ('url', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.RichTextBlock()), ('heading2', wagtail.wagtailcore.blocks.RichTextBlock()), ('description', wagtail.wagtailcore.blocks.RichTextBlock()), ('background_image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('url', wagtail.wagtailcore.blocks.URLBlock())))))),
        ),
    ]
