# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0017_reduce_focal_point_key_max_length'),
        ('home', '0002_auto_20170218_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridhomepage',
            name='background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='gridhomepage',
            name='summary',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gridhomepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('page', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock()), ('description', wagtail.wagtailcore.blocks.RichTextBlock()), ('background_image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('page', wagtail.wagtailcore.blocks.PageChooserBlock())))), ('url', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock()), ('description', wagtail.wagtailcore.blocks.RichTextBlock()), ('background_image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('url', wagtail.wagtailcore.blocks.URLBlock())))))),
        ),
    ]
